rabbit1:
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/rmq:2
  hostname: rabbit1
  restart: always
  labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  environment:
   - ERLANG_COOKIE=abcdefg
  ports:
   - "5672:5672"
   - "15672:15672"
rabbit2:
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/rmq:2
  hostname: rabbit2
  restart: always
  labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  links:
   - rabbit1
  environment:
   - ERLANG_COOKIE=abcdefg
   - CLUSTER_WITH=rabbit1
  ports:
   - "5673:5672"
   - "15673:15672"
